services:
  - type: web
    name: shruti-music
    env: python
    region: oregon
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python3 -m ShrutiMusic
    autoDeploy: true

    envVars:
      - key: API_ID
        value: 29448785
      - key: API_HASH
        value: 599574f6aff0a09ebb76305b58e7e9c2
      - key: API_KEY
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_DB_URI
        value: mongodb+srv://pusers:nycreation@nycreation.pd4klp1.mongodb.net/?retryWrites=true&w=majority&appName=NYCREATION
      - key: OWNER_ID
        value: 7574330905
      - key: OWNER_USERNAME
        value: WTF_WhyMeeh
      - key: BOT_USERNAME
        value: ShrutixMusicBot
      - key: UPSTREAM_REPO
        value: https://github.com/NoxxOP/ShrutiMusic
      - key: STRING_SESSION
        sync: false
      - key: GIT_TOKEN
        sync: false
      - key: HEROKU_API_KEY
        sync: false
      - key: HEROKU_APP_NAME
        sync: false
      - key: LOG_GROUP_ID
        value: -1002321189618
      - key: SUPPORT_GROUP
        value: https://t.me/ShrutiBotsupport
      - key: SUPPORT_CHANNEL
        value: https://t.me/ShrutiBots
      - key: INSTAGRAM
        value: https://instagram.com/yaduwanshi_nand
      - key: YOUTUBE
        value: https://youtube.com/@NandEditz
      - key: GITHUB
        value: https://github.com/NoxxOP
      - key: DONATE
        value: https://t.me/ShrutiBots/91
      - key: START_IMG_URL
        sync: false
